# Configuration for centralized training experiments

experiment:
  name: "centralized-anomaly-detection"
  description: "Centralized baseline for C2 beaconing detection"
  tracking_uri: null # Use local file store if null

data:
  dataset: "ctu13" # Options: ctu13, ugr16
  data_path: "data/processed"
  features_to_drop:
    - "StartTime"
    - "SrcAddr"
    - "DstAddr"
    - "Label"
    - "scenario"

model:
  type: "neural_network" # Options: random_forest, xgboost, neural_network

  # Random Forest parameters
  random_forest:
    n_estimators: 100
    max_depth: null
    min_samples_split: 2
    min_samples_leaf: 1
    class_weight: "balanced"
    random_state: 42
    n_jobs: -1

  # XGBoost parameters
  xgboost:
    n_estimators: 100
    max_depth: 6
    learning_rate: 0.3
    subsample: 1.0
    colsample_bytree: 1.0
    scale_pos_weight: null # Auto-calculated from data if null
    random_state: 42
    n_jobs: -1
    early_stopping_rounds: 10

  # Neural Network parameters
  neural_network:
    hidden_dims: [128, 64, 32]
    dropout_rate: 0.3
    learning_rate: 0.001
    batch_size: 256
    epochs: 50
    early_stopping_patience: 5
    class_weight: null # Auto-calculated if null
    random_state: 42

training:
  random_state: 42
  verbose: true

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

output:
  model_dir: "models"
  results_dir: "results"
  plots_dir: "plots"
